# Generated by Django 5.1.4 on 2025-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_uz',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='district',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_bot',
            field=models.CharField(default='https://t.me/', max_length=100, verbose_name='Телеграм-бот'),
        ),
    ]
