# Generated by Django 5.1.4 on 2025-01-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='video_length',
            field=models.FloatField(default=0, verbose_name='Продолжительность видео'),
        ),
        migrations.AddField(
            model_name='training',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='trainingmedia',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
    ]
