# Generated by Django 5.1.4 on 2025-01-11 19:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_training_video_length_training_view_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiltyperson',
            options={'ordering': ('-created_at',), 'verbose_name': 'Виновное лицо', 'verbose_name_plural': 'Виновное лицо'},
        ),
        migrations.AlterModelOptions(
            name='violationfile',
            options={'ordering': ('-created_at',), 'verbose_name': 'Файл нарушения', 'verbose_name_plural': 'Файлы нарушений'},
        ),
        migrations.AlterField(
            model_name='guiltyperson',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='guiltyperson',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='guiltyperson',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='guiltyperson',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.violationreport', verbose_name='Отчет о нарушении'),
        ),
        migrations.AlterField(
            model_name='violationfile',
            name='file',
            field=models.FileField(upload_to='violation_report/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png', 'mp4'), message='File must be in (pdf, jpg, jpeg, png, mp4)')], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='violationfile',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.violationreport', verbose_name='Нарушение'),
        ),
        migrations.AlterField(
            model_name='violationreport',
            name='informant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта информатора'),
        ),
        migrations.AlterField(
            model_name='violationreport',
            name='informant_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное имя информатора'),
        ),
        migrations.AlterField(
            model_name='violationreport',
            name='informant_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона информатора'),
        ),
        migrations.AlterField(
            model_name='violationreport',
            name='is_anonim',
            field=models.BooleanField(default=False, verbose_name='Аноним'),
        ),
    ]
