# Generated by Django 5.1.4 on 2025-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_organization_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='telegram_bot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм-бот'),
        ),
    ]
