# Generated by Django 5.1.4 on 2025-04-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_organization_telegram_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honestytestcategory',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='honestytestcategory',
            name='name_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='honestytestcategory',
            name='name_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='honestytestcategory',
            name='name_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Название категории'),
        ),
    ]
