# Generated by Django 5.1.4 on 2025-01-14 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_guiltyperson_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honestytestresult',
            name='percent',
        ),
        migrations.AddField(
            model_name='honestytestcategory',
            name='in_term',
            field=models.BooleanField(default=True, verbose_name='B перспективе'),
        ),
        migrations.AlterField(
            model_name='honestytestcategory',
            name='image',
            field=models.ImageField(upload_to='honesty_test/category', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='honestytestresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='services.honestytest', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='honestyteststatistic',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='honestyteststatistic',
            name='test_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stats_test_type', to='services.honestytestcategory', verbose_name='Тип теста'),
        ),
        migrations.AddConstraint(
            model_name='honestytestanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_true', True)), fields=('question',), name='Only one answer should be true for one question'),
        ),
    ]
