# Generated by Django 5.1.4 on 2025-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_honestytestresult_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptionrisk',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='excel_url',
            field=models.URLField(verbose_name='URL-адрес Эксель'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='form_url',
            field=models.URLField(verbose_name='URL-адрес Формы'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='image',
            field=models.ImageField(upload_to='corruption_risk/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Closed')], default=1, verbose_name='Статус'),
        ),
    ]
