# Generated by Django 5.1.4 on 2025-01-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_announcementcategory_remove_news_view_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorruptionRiskMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=60, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='corruption_risk/media', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Коррупционный риск СМИ',
                'verbose_name_plural': 'Коррупционный риск СМИ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='trainingmedia',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='URL-адрес видео на YouTube'),
        ),
    ]
