# Generated by Django 5.1.4 on 2025-01-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_corruptionriskmedia_alter_trainingmedia_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honestytest',
            options={'ordering': ('?',), 'verbose_name': 'Тест на честность', 'verbose_name_plural': 'Тест на честность'},
        ),
        migrations.AlterModelOptions(
            name='honestytestanswer',
            options={'ordering': ('?',), 'verbose_name': 'Ответ на тест на честность', 'verbose_name_plural': 'Ответ на тест на честность'},
        ),
    ]
