# Generated by Django 5.1.4 on 2025-01-17 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_honestytest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория раздаточного материала',
                'verbose_name_plural': 'Категории раздаточных материало',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Handout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='handout/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'zip', 'xls', 'xlsx'])], verbose_name='Файл')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.handoutcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Раздаточный материал',
                'verbose_name_plural': 'Раздаточные материалы',
                'ordering': ('-created_at',),
            },
        ),
    ]
