# Generated by Django 5.1.4 on 2025-01-17 20:56

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_handoutcategory_handout'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='announcementcategory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categoryorganization',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categoryorganization',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='categoryorganization',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='name_uz',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='result_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='result_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='result_uz',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='short_desc_en',
            field=models.TextField(max_length=120, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='short_desc_ru',
            field=models.TextField(max_length=120, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='corruptionrisk',
            name='short_desc_uz',
            field=models.TextField(max_length=120, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='corruptionriskmedia',
            name='filename_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='corruptionriskmedia',
            name='filename_ru',
            field=models.CharField(max_length=60, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='corruptionriskmedia',
            name='filename_uz',
            field=models.CharField(max_length=60, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='author_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_author_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Автор издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_type_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_type_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='edition_type_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Тип издания'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='name_uz',
            field=models.CharField(max_length=80, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='electronlibrarycategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='electronlibrarycategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='electronlibrarycategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handout',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handout',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handout',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handoutcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handoutcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='handoutcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='advice_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Cовет'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='advice_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Cовет'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='advice_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Cовет'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='question_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='question_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='honestytest',
            name='question_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='honestytestanswer',
            name='answer_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='honestytestanswer',
            name='answer_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='honestytestanswer',
            name='answer_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='honestytestcategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='honestytestcategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='honestytestcategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profession',
            name='name_uz',
            field=models.CharField(max_length=80, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='case_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Дилемма'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='case_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Дилемма'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='case_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Дилемма'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='professionalethics',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='name_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='name_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='name_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='training',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='training',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='training',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='training',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='training',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='training',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='filename_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='filename_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='filename_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='video_title_en',
            field=models.CharField(blank=True, null=True, verbose_name='Название видео'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='video_title_ru',
            field=models.CharField(blank=True, null=True, verbose_name='Название видео'),
        ),
        migrations.AddField(
            model_name='trainingmedia',
            name='video_title_uz',
            field=models.CharField(blank=True, null=True, verbose_name='Название видео'),
        ),
    ]
