# Generated by Django 5.1.4 on 2025-01-20 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_announcement_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handout',
            name='type',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='file',
            field=models.FileField(upload_to='handout/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'zip', 'xls'])], verbose_name='Файл'),
        ),
    ]
