# Generated by Django 5.1.4 on 2025-01-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_handout_type_alter_handout_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptionrisk',
            name='short_desc',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='short_desc_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='short_desc_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='corruptionrisk',
            name='short_desc_uz',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.CharField(max_length=400, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description_uz',
            field=models.CharField(max_length=400, null=True, verbose_name='Краткое описание'),
        ),
    ]
