# Generated by Django 5.1.4 on 2025-01-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_honestytestresult_answer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='honestytestanswer',
            name='Only one answer should be true for one question',
        ),
    ]
