# Generated by Django 5.1.4 on 2025-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_honestytestanswer_only_one_answer_should_be_true_for_one_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronlibrary',
            name='short_description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='electronlibrary',
            name='short_description_uz',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Краткое описание'),
        ),
    ]
