# Generated by Django 5.1.4 on 2025-01-28 14:45

import authentication.utils
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_agent', models.CharField(max_length=220, verbose_name='Пользовательский агент')),
                ('ip_address', models.CharField(max_length=15, verbose_name='IP-адрес')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=250, verbose_name='Пароль')),
                ('phone_number', models.CharField(max_length=14, validators=[authentication.utils.phone_number_validation], verbose_name='Номер телефона')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'Officer')], default=3, verbose_name='Роль')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='Время входа')),
                ('status', models.IntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Rejected')], default=1, verbose_name='Статус')),
                ('is_active', models.IntegerField(choices=[(1, 'Active'), (2, 'Block')], default=1)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContentViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.IntegerField(default=0, verbose_name='ID контента')),
                ('content_type', models.IntegerField(choices=[(1, 'Announcement'), (2, 'News'), (3, 'Training')], verbose_name='Тип контентa')),
                ('view_day', models.DateField(default=django.utils.timezone.now, verbose_name='Дата просмотра')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Просмотр контента',
                'verbose_name_plural': 'Просмотры контента',
                'ordering': ('-created_at',),
            },
        ),
    ]
