# Generated by Django 5.1.4 on 2025-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verify',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Block')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время входа'),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
