# Generated by Django 5.1.4 on 2025-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ip_address',
            field=models.CharField(max_length=100, verbose_name='IP-адрес'),
        ),
    ]
