# Generated by Django 5.1.4 on 2025-01-16 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_active_remove_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_id', models.IntegerField(default=0, verbose_name='ID контента')),
                ('content_type', models.IntegerField(choices=[(1, 'Announcement'), (2, 'News'), (3, 'Training')], verbose_name='Тип контентa')),
                ('view_day', models.DateField(default=django.utils.timezone.now, verbose_name='Дата просмотра')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Просмотр контента',
                'verbose_name_plural': 'Просмотры контента',
                'ordering': ('-created_at',),
            },
        ),
    ]
