# Generated by Django 5.1.4 on 2025-01-28 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('short_description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('short_description_uz', models.TextField(max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_ru', models.TextField(max_length=500, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.TextField(max_length=500, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('type', models.IntegerField(choices=[(1, 'About Conflict of Interest'), (2, 'About Corruption Risk'), (3, 'About Promotion and Useful Information')], default=1, verbose_name='Категория')),
                ('is_published', models.BooleanField(default=True, verbose_name='Oпубликован')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('short_description_uz', models.CharField(max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(max_length=300, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Oпубликован')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatisticYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Статистика по году',
                'verbose_name_plural': 'Статистика по годам',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RainbowStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Высокий процент')),
                ('satisfactory', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Удовлетворительный процент')),
                ('unsatisfactory', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Неудовлетворительный процент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statisticyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Статистика по радуге',
                'verbose_name_plural': 'Статистика по радуге',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='QuarterlyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название')),
                ('first_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(35)], verbose_name='Первый квартал')),
                ('second_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Второй квартал')),
                ('third_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Третий квартал')),
                ('fourth_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Четвертый квартал')),
                ('fifth_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Пятый квартал')),
                ('last_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Предыдущий год')),
                ('this_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Текущий год')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statisticyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Квартальная статистика',
                'verbose_name_plural': 'Квартальная статистика',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='LinerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('name_uz', models.CharField(max_length=300, null=True, verbose_name='Наименование')),
                ('name_ru', models.CharField(max_length=300, null=True, verbose_name='Наименование')),
                ('name_en', models.CharField(max_length=300, null=True, verbose_name='Наименование')),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statisticyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Линейная статистика',
                'verbose_name_plural': 'Линейная статистика',
                'ordering': ('-year',),
            },
        ),
    ]
