# Generated by Django 5.1.4 on 2025-01-16 20:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2025)], verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Статистика по году',
                'verbose_name_plural': 'Статистика по годам',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='RainbowStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Высокий процент')),
                ('satisfactory', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Удовлетворительный процент')),
                ('unsatisfactory', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Неудовлетворительный процент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statisticyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Статистика по радуге',
                'verbose_name_plural': 'Статистика по радуге',
                'ordering': ('-year',),
            },
        ),
        migrations.CreateModel(
            name='LinerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.statisticyear', verbose_name='Год')),
            ],
            options={
                'verbose_name': 'Линейная статистика',
                'verbose_name_plural': 'Линейная статистика',
                'ordering': ('-year',),
            },
        ),
    ]
