# Generated by Django 5.1.4 on 2025-01-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_statisticyear_rainbowstatistic_linerstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='link',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='short_desc',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Oпубликован'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='type',
            field=models.IntegerField(choices=[(1, 'About Conflict of Interest'), (2, 'About Corruption Risk'), (3, 'About Promotion and Useful Information')], default=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner/', verbose_name='Изображение'),
        ),
    ]
