# Generated by Django 5.1.4 on 2025-01-17 20:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_aboutus_link_remove_aboutus_short_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description_ru',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='short_description_uz',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='banner',
            name='short_description_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='short_description_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='short_description_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='Отвечать'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='linerstatistic',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='linerstatistic',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='linerstatistic',
            name='name_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
